services:
  # Node.js Express application
  backend-nodejs:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend-nodejs
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    volumes:
      - ./backend:/app/backend
      - ./views:/app/views
      - ./partials:/app/partials
      - ./public:/app/public
      - /app/backend/node_modules
    # No ports exposed - only nginx can access this container
    networks:
      - app-network

  # nginx reverse proxy
  # To test this without routing traffic through the proxy server
  # Add the following
  # ports:
  #   - "80:80"
  proxy:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: proxy
    restart: unless-stopped
    volumes:
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
    depends_on:
      - backend-nodejs
    networks:
      - app-network

  # Newt Tunnel to Route All Traffic
  # To test this locally, comment this out and add ports to the proxy service
  tunnel:
    image: fosrl/newt
    container_name: newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT=${PANGOLIN_ENDPOINT}
      - NEWT_ID=${NEWT_ID}
      - NEWT_SECRET=${NEWT_SECRET}
    depends_on:
      - proxy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
